version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - legal_trainer:1.0
    command: gunicorn LegalTrainer.wsgi:application --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=LegalTrainer.settings.prod

    volumes:
      - static_volume:/app/static/
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx_conf/
    container_name: lt_nginx
    image: lt_nginx
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - web
    ports:
      - "1337:80"
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: