# Generated by Django 4.1.5 on 2023-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_useranswer_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
