# Generated by Django 4.1.5 on 2023-03-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_testanswer_usertestmodel_remove_test_is_answered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.question'),
        ),
    ]
