# Generated by Django 4.1.5 on 2023-03-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_test_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.test'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='testanswer',
            name='answer',
            field=models.ManyToManyField(blank=True, to='quiz.answer'),
        ),
    ]
