# Generated by Django 4.1.5 on 2023-03-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_testanswer_test_remove_testanswer_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testanswer',
            old_name='answer',
            new_name='answers',
        ),
    ]
