# Generated by Django 4.1.5 on 2023-03-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_usertestmodel_answers_usertestmodel_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='test_questions', to='quiz.question'),
        ),
    ]
