# Generated by Django 4.1.5 on 2023-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_test_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestmodel',
            name='answers',
        ),
        migrations.AddField(
            model_name='usertestmodel',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
