# Generated by Django 4.1.5 on 2023-03-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_usertestmodel_answers_usertestmodel_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answers', models.ManyToManyField(blank=True, to='quiz.answer')),
                ('user_test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.usertestmodel')),
            ],
        ),
    ]
