# Generated by Django 4.1.5 on 2023-08-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_usertestanswer_delete_testanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAnswer',
        ),
    ]
